//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExcelPerplexityVSTO
{
    using System = global::System;
    using Office = global::Microsoft.Office.Core;
    using Excel = global::Microsoft.Office.Interop.Excel;

    [System.Runtime.InteropServices.ComVisible(true)]
    [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)]
    [global::Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class Globals
    {
        internal static global::Microsoft.Office.Tools.Excel.Factory Factory;
        internal static ThisAddIn ThisAddIn;

        private static void InitializeFactory(global::Microsoft.Office.Tools.Excel.Factory factory)
        {
            if (Globals.Factory == null)
            {
                Globals.Factory = factory;
            }
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCode()]
    [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0")]
    partial class ThisAddIn
    {
        internal Excel.Application Application { get; set; }
        internal global::Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes { get; set; }

        internal event System.EventHandler Startup;
        internal event System.EventHandler Shutdown;

        #region Component Designer generated code

        private void InitializeComponent()
        {
        }

        #endregion

        #region VSTO generated code

        private void FinishInitialization()
        {
            this.InternalStartup();
        }

        internal void Initialize(Excel.Application application, global::Microsoft.Office.Tools.CustomTaskPaneCollection customTaskPanes)
        {
            Globals.ThisAddIn = this;
            this.Application = application;
            this.CustomTaskPanes = customTaskPanes;
            this.FinishInitialization();
        }

        internal void RaiseStartup()
        {
            if (this.Startup != null)
            {
                this.Startup(this, System.EventArgs.Empty);
            }
        }

        internal void RaiseShutdown()
        {
            if (this.Shutdown != null)
            {
                this.Shutdown(this, System.EventArgs.Empty);
            }
        }

        #endregion
    }
}
#pragma warning restore 414
